# -*- coding: utf-8 -*-
"""netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDU2rX-k6ztQ7P5Oui4gT0xSUvwIYwAs
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("netflix_titles.csv")
df.head()

df.info()
df.isnull().sum()

df.dropna(subset=['country', 'rating'], inplace=True)

sns.countplot(x='type', data=df)
plt.title("Movies vs TV Shows")
plt.show()

top_countries = df['country'].value_counts().head(10)

top_countries.plot(kind='bar')
plt.title("Top 10 Countries")
plt.show()

df['release_year'].value_counts().sort_index().plot()
plt.title("Content Released Over Years")
plt.show()

sns.countplot(y='rating', data=df, order=df['rating'].value_counts().index)
plt.title("Ratings Distribution")
plt.show()

df['release_year'].value_counts().sort_index().plot(figsize=(10,5))
plt.title("Growth of Netflix Content Over Years")
plt.xlabel("Year")
plt.ylabel("Number of Titles")
plt.show()

genres = df['listed_in'].str.split(', ', expand=True).stack()
top_genres = genres.value_counts().head(10)

top_genres.plot(kind='barh')
plt.title("Top 10 Genres on Netflix")
plt.show()

df['type'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Movies vs TV Shows Distribution")
plt.ylabel('')
plt.show()

